### ISSUE TITLE
4.1.0 build fails with error: could not convert 'gnuradio::get_initial_sptr(T*) [with T = gr::op25_repeater::frame_assembler_impl]()' from 'std::shared_ptr<gr::op25_repeater::frame_assembler_impl>' to 'gr::op25_repeater::frame_assembler::sptr' {aka 'boost::shared_ptr<gr::op25_repeater::frame_assembler>'}

### ISSUE THREAD

**Issue by mldulaney** [robotastic/trunk-recorder#561]
/builddir/build/BUILD/trunk-recorder-4.1.0/lib/op25_repeater/lib/frame_assembler_impl.cc: In static member function 'static gr::op25_repeater::frame_assembler::sptr gr::op25_repeater::frame_assembler::make(int, const char*, int, int, gr::msg_queue::sptr)':
/builddir/build/BUILD/trunk-recorder-4.1.0/lib/op25_repeater/lib/frame_assembler_impl.cc:77:21: error: could not convert 'gnuradio::get_initial_sptr(T*) [with T = gr::op25_repeater::frame_assembler_impl]()' from 'std::shared_ptr<gr::op25_repeater::frame_assembler_impl>' to 'gr::op25_repeater::frame_assembler::sptr' {aka 'boost::shared_ptr<gr::op25_repeater::frame_assembler>'}
   76 |                 return gnuradio::get_initial_sptr
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
   77 |                     (new frame_assembler_impl(sys_num, options, debug, msgq_id, queue));
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     std::shared_ptr<gr::op25_repeater::frame_assembler_impl>

**Comment by JoeGilkey** [comment]
@mldulaney what version of GnuRadio is on your system?

**Comment by mldulaney** [comment]
3.9.2.0-7.fc35

**Comment by JoeGilkey** [comment]
Ah, try using 3.8.x instead. I don't think the OP25 code has been updated to support 3.9 yet.

**Comment by robotastic** [comment]
@mldulaney I merged in a PR for Fedora 35 that has gnuradio 3.9 in it... give it a try and let me know if it works. Just `pull` the latest version of Trunk Recorder and rebuild.

**Comment by toddejohnson** [comment]
I also got this when updating the AUR package for 4.1.0:
```
[ 30%] Building CXX object lib/op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/frame_assembler_impl.cc.o
/build/trunk-recorder/src/trunk-recorder-4.1.0/lib/op25_repeater/lib/frame_assembler_impl.cc: In static member function ‘static gr::op25_repeater::frame_assembler::sptr gr::op25_repeater::frame_assembler::make(int, const char*, int, int, gr::msg_queue::sptr)’:
/build/trunk-recorder/src/trunk-recorder-4.1.0/lib/op25_repeater/lib/frame_assembler_impl.cc:77:21: error: could not convert ‘gnuradio::get_initial_sptr(T*) [with T = gr::op25_repeater::frame_assembler_impl]()’ from ‘std::shared_ptr<gr::op25_repeater::frame_assembler_impl>’ to ‘gr::op25_repeater::frame_assembler::sptr’ {aka ‘boost::shared_ptr<gr::op25_repeater::frame_assembler>’}
   76 |                 return gnuradio::get_initial_sptr
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
   77 |                     (new frame_assembler_impl(sys_num, options, debug, msgq_id, queue));
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     std::shared_ptr<gr::op25_repeater::frame_assembler_impl>
make[2]: *** [lib/op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/build.make:174: lib/op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/frame_assembler_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: lib/op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Compiling AUR trunk-recorder-git r1706.8072483 was successful this morning. Any chance you would be interested in a new release or could you point me to the commit/PR so I can make a patch that would allow 4.1.0 to compile with GR3.9?

**Comment by toddejohnson** [comment]
Doh! Looks like #560 is what I'm looking for. to fix this?

**Comment by toddejohnson** [comment]
For the [AUR package](https://aur.archlinux.org/packages/trunk-recorder) I stole [a patch](https://aur.archlinux.org/cgit/aur.git/tree/trunk-recorder-pr560.patch?h=trunk-recorder) from #560 that has resolved this issue for me if it helps. Excited to have 4.1.0!!

**Comment by robotastic** [comment]
Cool! I will close for now. Let me know if something else breaks.

**Comment by mldulaney** [comment]
Confirmed all is good.
